export const pricesByExchange = {
  'Binance': {
    'BTC-USDT': 'BTCUSDT', 'ETH-USDT': 'ETHUSDT', 'ETH-BTC': 'ETHBTC',
    'LTC-USDT': 'LTCUSDT', 'BCH-USDT': 'BCHUSDT', 'BNB-USDT': 'BNBUSDT',
    'SOL-USDT': 'SOLUSDT', 'ADA-USDT': 'ADAUSDT', 'XRP-USDT': 'XRPUSDT',
    'DOT-USDT': 'DOTUSDT', 'DOGE-USDT': 'DOGEUSDT', 'AVAX-USDT': 'AVAXUSDT',
    'MATIC-USDT': 'MATICUSDT', 'POL-USDT': 'MATICUSDT', // alias
    'SHIB-USDT': 'SHIBUSDT', 'TRX-USDT': 'TRXUSDT', 'LINK-USDT': 'LINKUSDT',
    'ATOM-USDT': 'ATOMUSDT', 'XMR-USDT': 'XMRUSDT', 'WBTC-USDT': 'WBTCUSDT',
    'UNI-USDT': 'UNIUSDT', 'XTZ-USDT': 'XTZUSDT', 'FIL-USDT': 'FILUSDT',
    'EOS-USDT': 'EOSUSDT', 'AAVE-USDT': 'AAVEUSDT', 'SAND-USDT': 'SANDUSDT',
    'APE-USDT': 'APEUSDT', 'GRT-USDT': 'GRTUSDT', 'ETC-USDT': 'ETCUSDT',
    'NEAR-USDT': 'NEARUSDT', 'EGLD-USDT': 'EGLDUSDT', 'ZEC-USDT': 'ZECUSDT',
    'STX-USDT': 'STXUSDT', 'ALGO-USDT': 'ALGOUSDT', 'SNX-USDT': 'SNXUSDT',
    'RUNE-USDT': 'RUNEUSDT', 'MKR-USDT': 'MKRUSDT', 'CRV-USDT': 'CRVUSDT',
    'DYDX-USDT': 'DYDXUSDT', 'LDO-USDT': 'LDOUSDT', '1INCH-USDT': '1INCHUSDT',
    'COMP-USDT': 'COMPUSDT', 'BTC-USD': 'BTCUSD', 'ETH-USD': 'ETHUSD',
    'LTC-USD': 'LTCUSD', 'SOL-USD': 'SOLUSD', 'USDC-USDT': 'USDCUSDT',
    'DAI-USDT': 'DAIUSDT', 'ARB-USDT': 'ARBUSDT', 'ARB-BTC': 'ARBBTC',
    'TON-USDT': 'TONUSDT', 'TON-BTC': 'TONBTC', 'OP-USDT': 'OPUSDT', 'OP-BTC': 'OPBTC',    // Cross-asset
    'LTC-BTC': 'LTCBTC', 'XRP-BTC': 'XRPBTC', 'BNB-BTC': 'BNBBTC',
    'SOL-BTC': 'SOLBTC', 'ADA-BTC': 'ADABTC'
  },
  'Kraken': {
    'BTC-USDT': 'XXBTZUSD',
    'ETH-USDT': 'XETHZUSD',
    'ETH-BTC': 'XETHXXBT',
    'LTC-USDT': 'XLTCZUSD',
    'BCH-USDT': 'BCHUSD',
    'BNB-USDT': null,
    'SOL-USDT': 'SOLUSD',
    'ADA-USDT': 'ADAUSD',
    'XRP-USDT': 'XXRPZUSD',
    'DOT-USDT': 'DOTUSD',
    'DOGE-USDT': 'DOGEUSD',
    'AVAX-USDT': 'AVAXUSD',
    'MATIC-USDT': 'MATICUSD',
    'SHIB-USDT': 'SHIBUSD',
    'TRX-USDT': 'TRXUSD',
    'LINK-USDT': 'LINKUSD',
    'ATOM-USDT': 'ATOMUSD',
    'XMR-USDT': 'XXMRZUSD',
    'WBTC-USDT': 'WBTCUSD',
    'UNI-USDT': 'UNIUSD',
    'XTZ-USDT': 'XTZUSD',
    'FIL-USDT': 'FILUSD',
    'EOS-USDT': 'EOSUSD',
    'AAVE-USDT': 'AAVEUSD',
    'SAND-USDT': null,
    'APE-USDT': null,
    'GRT-USDT': null,
    'ETC-USDT': 'ETCUSD',
    'NEAR-USDT': 'NEARUSD',
    'EGLD-USDT': null,
    'ZEC-USDT': 'ZECUSD',
    'STX-USDT': null,
    'ALGO-USDT': 'ALGOUSD',
    'SNX-USDT': null,
    'RUNE-USDT': null,
    'MKR-USDT': 'MKRUSD',
    'CRV-USDT': null,
    'DYDX-USDT': null,
    'LDO-USDT': null,
    '1INCH-USDT': null,
    'COMP-USDT': 'COMPUSD',
    'BTC-USD': 'XXBTZUSD',
    'ETH-USD': 'XETHZUSD',
    'LTC-USD': 'XLTCZUSD',
    'SOL-USD': 'SOLUSD',
    'USDC-USDT': null,
    'DAI-USDT': null,
    // Cross-asset pairs:
    'ETH-BTC': 'XETHXXBT',
    'LTC-BTC': 'XLTCXXBT',
    'XRP-BTC': 'XXRPXXBT',
    'BNB-BTC': null,
    'SOL-BTC': 'SOLXXBT',
    'ADA-BTC': 'ADAXXBT'
  },
  'Bitfinex': {
    'BTC-USDT': 'BTCUSD',
    'ETH-USDT': 'ETHUSD',
    'ETH-BTC': 'ETHBTC',
    'LTC-USDT': 'LTCUSD',
    'BCH-USDT': 'BCHUSD',
    'BNB-USDT': null,
    'SOL-USDT': 'SOLUSD',
    'ADA-USDT': 'ADAUSD',
    'XRP-USDT': 'XRPUSD',
    'DOT-USDT': 'DOTUSD',
    'DOGE-USDT': null,
    'AVAX-USDT': 'AVAXUSD',
    'MATIC-USDT': null,
    'SHIB-USDT': null,
    'TRX-USDT': 'TRXUSD',
    'LINK-USDT': 'LINKUSD',
    'ATOM-USDT': 'ATOMUSD',
    'XMR-USDT': 'XMRUSD',
    'WBTC-USDT': null,
    'UNI-USDT': 'UNIUSD',
    'XTZ-USDT': 'XTZUSD',
    'FIL-USDT': 'FILUSD',
    'EOS-USDT': 'EOSUSD',
    'AAVE-USDT': 'AAVEUSD',
    'SAND-USDT': null,
    'APE-USDT': null,
    'GRT-USDT': null,
    'ETC-USDT': 'ETCUSD',
    'NEAR-USDT': null,
    'EGLD-USDT': null,
    'ZEC-USDT': 'ZECUSD',
    'STX-USDT': null,
    'ALGO-USDT': null,
    'SNX-USDT': null,
    'RUNE-USDT': null,
    'MKR-USDT': 'MKRUSD',
    'CRV-USDT': null,
    'DYDX-USDT': null,
    'LDO-USDT': null,
    '1INCH-USDT': null,
    'COMP-USDT': 'COMPUSD',
    'BTC-USD': 'BTCUSD',
    'ETH-USD': 'ETHUSD',
    'LTC-USD': 'LTCUSD',
    'SOL-USD': 'SOLUSD',
    'USDC-USDT': null,
    'DAI-USDT': null,
    // Cross-asset pairs:
    'ETH-BTC': 'ETHBTC',
    'LTC-BTC': 'LTCBTC',
    'XRP-BTC': 'XRPBTC',
    'BNB-BTC': 'BNBBTC',
    'SOL-BTC': 'SOLBTC',
    'ADA-BTC': 'ADABTC'
  },
  'Huobi': {
    'BTC-USDT': 'btcusdt',
    'ETH-USDT': 'ethusdt',
    'ETH-BTC': 'ethbtc',
    'LTC-USDT': 'ltcusdt',
    'BCH-USDT': 'bchusdt',
    'BNB-USDT': null,
    'SOL-USDT': 'solusdt',
    'ADA-USDT': 'adausdt',
    'XRP-USDT': 'xrpusdt',
    'DOT-USDT': 'dotusdt',
    'DOGE-USDT': 'dogeusdt',
    'AVAX-USDT': 'avaxusdt',
    'MATIC-USDT': null,
    'SHIB-USDT': 'shibusdt',
    'TRX-USDT': 'trxusdt',
    'LINK-USDT': 'linkusdt',
    'ATOM-USDT': 'atomusdt',
    'XMR-USDT': 'xmrusdt',
    'WBTC-USDT': null,
    'UNI-USDT': 'uniusdt',
    'XTZ-USDT': 'xtzusdt',
    'FIL-USDT': 'filusdt',
    'EOS-USDT': 'eosusdt',
    'AAVE-USDT': 'aaveusdt',
    'SAND-USDT': 'sandusdt',
    'APE-USDT': null,
    'GRT-USDT': null,
    'ETC-USDT': 'etcusdt',
    'NEAR-USDT': 'nearusdt',
    'EGLD-USDT': null,
    'ZEC-USDT': 'zecusdt',
    'STX-USDT': null,
    'ALGO-USDT': 'algousdt',
    'SNX-USDT': null,
    'RUNE-USDT': null,
    'MKR-USDT': 'mkrusdt',
    'CRV-USDT': null,
    'DYDX-USDT': null,
    'LDO-USDT': null,
    '1INCH-USDT': null,
    'COMP-USDT': 'compusdt',
    'ETH-BTC': 'ethbtc',
    'LTC-BTC': 'ltcbtc',
    'XRP-BTC': 'xrp',
    'BNB-BTC': null,
    'SOL-BTC': 'solbtc',
    'ADA-BTC': 'adabtc'
  },
  'OKEx': {
    'BTC-USDT': 'BTC-USDT',
    'ETH-USDT': 'ETH-USDT',
    'ETH-BTC': 'ETH-BTC',
    'LTC-USDT': 'LTC-USDT',
    'BCH-USDT': 'BCH-USDT',
    'BNB-USDT': 'BNB-USDT',
    'SOL-USDT': 'SOL-USDT',
    'ADA-USDT': 'ADA-USDT',
    'XRP-USDT': 'XRP-USDT',
    'DOT-USDT': 'DOT-USDT',
    'DOGE-USDT': 'DOGE-USDT',
    'AVAX-USDT': 'AVAX-USDT',
    'MATIC-USDT': 'MATIC-USDT',
    'SHIB-USDT': 'SHIB-USDT',
    'TRX-USDT': 'TRX-USDT',
    'LINK-USDT': 'LINK-USDT',
    'ATOM-USDT': 'ATOM-USDT',
    'XMR-USDT': 'XMR-USDT',
    'WBTC-USDT': 'WBTC-USDT',
    'UNI-USDT': 'UNI-USDT',
    'XTZ-USDT': 'XTZ-USDT',
    'FIL-USDT': 'FIL-USDT',
    'EOS-USDT': 'EOS-USDT',
    'AAVE-USDT': 'AAVE-USDT',
    'SAND-USDT': 'SAND-USDT',
    'APE-USDT': 'APE-USDT',
    'GRT-USDT': 'GRT-USDT',
    'ETC-USDT': 'ETC-USDT',
    'NEAR-USDT': 'NEAR-USDT',
    'EGLD-USDT': 'EGLD-USDT',
    'ZEC-USDT': 'ZEC-USDT',
    'STX-USDT': 'STX-USDT',
    'ALGO-USDT': 'ALGO-USDT',
    'SNX-USDT': 'SNX-USDT',
    'RUNE-USDT': 'RUNE-USDT',
    'MKR-USDT': 'MKR-USDT',
    'CRV-USDT': 'CRV-USDT',
    'DYDX-USDT': 'DYDX-USDT',
    'LDO-USDT': 'LDO-USDT',
    '1INCH-USDT': '1INCH-USDT',
    'COMP-USDT': 'COMP-USDT',
    'ETH-BTC': 'ETH-BTC'
  },
  'Gate.io': {
    'BTC-USDT': 'BTC_USDT',
    'ETH-USDT': 'ETH_USDT',
    'ETH-BTC': 'ETH_BTC',
    'LTC-USDT': 'LTC_USDT',
    'BCH-USDT': 'BCH_USDT',
    'BNB-USDT': 'BNB_USDT',
    'SOL-USDT': 'SOL_USDT',
    'ADA-USDT': 'ADA_USDT',
    'XRP-USDT': 'XRP_USDT',
    'DOT-USDT': 'DOT_USDT',
    'DOGE-USDT': 'DOGE_USDT',
    'AVAX-USDT': 'AVAX_USDT',
    'MATIC-USDT': 'MATIC_USDT',
    'SHIB-USDT': 'SHIB_USDT',
    'TRX-USDT': 'TRX_USDT',
    'LINK-USDT': 'LINK_USDT',
    'ATOM-USDT': 'ATOM_USDT',
    'XMR-USDT': 'XMR_USDT',
    'WBTC-USDT': 'WBTC_USDT',
    'UNI-USDT': 'UNI_USDT',
    'XTZ-USDT': 'XTZ_USDT',
    'FIL-USDT': 'FIL_USDT',
    'EOS-USDT': 'EOS_USDT',
    'AAVE-USDT': 'AAVE_USDT',
    'SAND-USDT': 'SAND_USDT',
    'APE-USDT': 'APE_USDT',
    'GRT-USDT': 'GRT_USDT',
    'ETC-USDT': 'ETC_USDT',
    'NEAR-USDT': 'NEAR_USDT',
    'EGLD-USDT': 'EGLD_USDT',
    'ZEC-USDT': 'ZEC_USDT',
    'STX-USDT': 'STX_USDT',
    'ALGO-USDT': 'ALGO_USDT',
    'SNX-USDT': 'SNX_USDT',
    'RUNE-USDT': 'RUNE_USDT',
    'MKR-USDT': 'MKR_USDT',
    'CRV-USDT': 'CRV_USDT',
    'DYDX-USDT': 'DYDX_USDT',
    'LDO-USDT': 'LDO_USDT',
    '1INCH-USDT': '1INCH_USDT',
    'COMP-USDT': 'COMP_USDT',
    'ETH-BTC': 'ETH_BTC'
  },
  'KuCoin': {
    'BTC-USDT': 'BTC-USDT',
    'ETH-USDT': 'ETH-USDT',
    'ETH-BTC': 'ETH-BTC',
    'LTC-USDT': 'LTC-USDT',
    'BCH-USDT': 'BCH-USDT',
    'BNB-USDT': 'BNB-USDT',
    'SOL-USDT': 'SOL-USDT',
    'ADA-USDT': 'ADA-USDT',
    'XRP-USDT': 'XRP-USDT',
    'DOT-USDT': 'DOT-USDT',
    'DOGE-USDT': 'DOGE-USDT',
    'AVAX-USDT': 'AVAX-USDT',
    'MATIC-USDT': 'MATIC-USDT',
    'SHIB-USDT': 'SHIB-USDT',
    'TRX-USDT': 'TRX-USDT',
    'LINK-USDT': 'LINK-USDT',
    'ATOM-USDT': 'ATOM-USDT',
    'XMR-USDT': 'XMR-USDT',
    'WBTC-USDT': 'WBTC-USDT',
    'UNI-USDT': 'UNI-USDT',
    'XTZ-USDT': 'XTZ-USDT',
    'FIL-USDT': 'FIL-USDT',
    'EOS-USDT': 'EOS-USDT',
    'AAVE-USDT': 'AAVE-USDT',
    'SAND-USDT': 'SAND-USDT',
    'APE-USDT': 'APE-USDT',
    'GRT-USDT': 'GRT-USDT',
    'ETC-USDT': 'ETC-USDT',
    'NEAR-USDT': 'NEAR-USDT',
    'EGLD-USDT': 'EGLD-USDT',
    'ZEC-USDT': 'ZEC-USDT',
    'STX-USDT': 'STX-USDT',
    'ALGO-USDT': 'ALGO-USDT',
    'SNX-USDT': 'SNX-USDT',
    'RUNE-USDT': 'RUNE-USDT',
    'MKR-USDT': 'MKR-USDT',
    'CRV-USDT': 'CRV-USDT',
    'DYDX-USDT': 'DYDX-USDT',
    'LDO-USDT': 'LDO-USDT',
    '1INCH-USDT': '1INCH-USDT',
    'COMP-USDT': 'COMP-USDT',
    'ETH-BTC': 'ETH-BTC',
    'ARB-USDT': 'ARB-USDT',
    'ARB-BTC': 'ARB-BTC',
    'TON-USDT': 'TON-USDT',
    'TON-BTC': 'TON-BTC',
    'OP-USDT': 'OP-USDT',
    'OP-BTC': 'OP-BTC',
  },
  'Bitstamp': {
    'BTC-USDT': 'btcusd',
    'ETH-USDT': 'ethusd',
    'ETH-BTC': 'ethbtc',
    'LTC-USDT': 'ltcusd',
    'BCH-USDT': 'bchusd',
    'BNB-USDT': null,
    'SOL-USDT': 'solusd',
    'ADA-USDT': 'adausd',
    'XRP-USDT': 'xrpusd',
    'DOT-USDT': 'dotusd',
    'DOGE-USDT': 'dogeusd',
    'AVAX-USDT': 'avaxusd',
    'MATIC-USDT': 'maticusd',
    'SHIB-USDT': 'shibusd',
    'TRX-USDT': 'trxusd',
    'LINK-USDT': 'linkusd',
    'ATOM-USDT': null,
    'XMR-USDT': 'xmrusd',
    'WBTC-USDT': 'wbtcusd',
    'UNI-USDT': 'uniusd',
    'XTZ-USDT': 'xtzusd',
    'FIL-USDT': null,
    'EOS-USDT': 'eosusd',
    'AAVE-USDT': 'aaveusd',
    'SAND-USDT': null,
    'APE-USDT': null,
    'GRT-USDT': null,
    'ETC-USDT': 'etcusd',
    'NEAR-USDT': null,
    'EGLD-USDT': null,
    'ZEC-USDT': 'zecusd',
    'STX-USDT': null,
    'ALGO-USDT': 'algousd',
    'SNX-USDT': null,
    'RUNE-USDT': null,
    'MKR-USDT': null,
    'CRV-USDT': null,
    'DYDX-USDT': null,
    'LDO-USDT': null,
    '1INCH-USDT': null,
    'COMP-USDT': null,
    'ETH-BTC': 'ethbtc'
  },
  'Gemini': {
    'BTC-USDT': 'btcusd',
    'ETH-USDT': 'ethusd',
    'ETH-BTC': 'ethbtc',
    'LTC-USDT': 'ltcusd',
    'BCH-USDT': 'bchusd',
    'BNB-USDT': null,
    'SOL-USDT': null,
    'ADA-USDT': null,
    'XRP-USDT': 'xrpusd',
    'DOT-USDT': 'dotusd',
    'DOGE-USDT': 'dogeusd',
    'AVAX-USDT': null,
    'MATIC-USDT': 'maticusd',
    'SHIB-USDT': null,
    'TRX-USDT': null,
    'LINK-USDT': null,
    'ATOM-USDT': null,
    'XMR-USDT': null,
    'WBTC-USDT': null,
    'UNI-USDT': null,
    'XTZ-USDT': null,
    'FIL-USDT': null,
    'EOS-USDT': null,
    'AAVE-USDT': null,
    'SAND-USDT': null,
    'APE-USDT': null,
    'GRT-USDT': null,
    'ETC-USDT': null,
    'NEAR-USDT': null,
    'EGLD-USDT': null,
    'ZEC-USDT': null,
    'STX-USDT': null,
    'ALGO-USDT': null,
    'SNX-USDT': null,
    'RUNE-USDT': null,
    'MKR-USDT': null,
    'CRV-USDT': null,
    'DYDX-USDT': null,
    'LDO-USDT': null,
    '1INCH-USDT': null,
    'COMP-USDT': null
  },
  'HitBTC': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    'LTC-USDT': 'LTCUSDT',
    'BCH-USDT': 'BCHUSDT',
    'BNB-USDT': 'BNBUSDT',
    'SOL-USDT': 'SOLUSDT',
    'ADA-USDT': 'ADAUSDT',
    'XRP-USDT': 'XRPUSDT',
    'DOT-USDT': 'DOTUSDT',
    'DOGE-USDT': 'DOGEUSDT',
    'AVAX-USDT': 'AVAXUSDT',
    'MATIC-USDT': 'MATICUSDT',
    'SHIB-USDT': 'SHIBUSDT',
    'TRX-USDT': 'TRXUSDT',
    'LINK-USDT': 'LINKUSDT',
    'ATOM-USDT': 'ATOMUSDT',
    'XMR-USDT': 'XMRUSDT',
    'WBTC-USDT': 'WBTCUSDT',
    'UNI-USDT': 'UNIUSDT',
    'XTZ-USDT': 'XTZUSDT',
    'FIL-USDT': 'FILUSDT',
    'EOS-USDT': 'EOSUSDT',
    'AAVE-USDT': 'AAVEUSDT',
    'SAND-USDT': 'SANDUSDT',
    'APE-USDT': 'APEUSDT',
    'GRT-USDT': 'GRTUSDT',
    'ETC-USDT': 'ETCUSDT',
    'NEAR-USDT': 'NEARUSDT',
    'EGLD-USDT': 'EGLDUSDT',
    'ZEC-USDT': 'ZECUSDT',
    'STX-USDT': 'STXUSDT',
    'ALGO-USDT': 'ALGOUSDT',
    'SNX-USDT': 'SNXUSDT',
    'RUNE-USDT': 'RUNEUSDT',
    'MKR-USDT': 'MKRUSDT',
    'CRV-USDT': 'CRVUSDT',
    'DYDX-USDT': 'DYDXUSDT',
    'LDO-USDT': 'LDOUSDT',
    '1INCH-USDT': '1INCHUSDT',
    'COMP-USDT': 'COMPUSDT',
    'USDC-USDT': 'USDCUSDT',
    'DAI-USDT': 'DAIUSDT',
    // Cross-asset pairs:
    'ETH-BTC': 'ETHBTC',
    'LTC-BTC': 'LTCBTC',
    'XRP-BTC': 'XRPBTC',
    'BNB-BTC': 'BNBBTC',
    'SOL-BTC': 'SOLBTC',
    'ADA-BTC': 'ADABTC'
  },
  'CoinEx': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    'LTC-USDT': 'LTCUSDT',
    'BCH-USDT': 'BCHUSDT',
    'BNB-USDT': 'BNBUSDT',
    'SOL-USDT': 'SOLUSDT',
    'ADA-USDT': 'ADAUSDT',
    'XRP-USDT': 'XRPUSDT',
    'DOT-USDT': 'DOTUSDT',
    'DOGE-USDT': 'DOGEUSDT',
    'AVAX-USDT': 'AVAXUSDT',
    'MATIC-USDT': 'MATICUSDT',
    'SHIB-USDT': 'SHIBUSDT',
    'TRX-USDT': 'TRXUSDT',
    'LINK-USDT': 'LINKUSDT',
    'ATOM-USDT': 'ATOMUSDT',
    'XMR-USDT': 'XMRUSDT',
    'WBTC-USDT': 'WBTCUSDT',
    'UNI-USDT': 'UNIUSDT',
    'XTZ-USDT': 'XTZUSDT',
    'FIL-USDT': 'FILUSDT',
    'EOS-USDT': 'EOSUSDT',
    'AAVE-USDT': 'AAVEUSDT',
    'SAND-USDT': 'SANDUSDT',
    'APE-USDT': 'APEUSDT',
    'GRT-USDT': 'GRTUSDT',
    'ETC-USDT': 'ETCUSDT',
    'NEAR-USDT': 'NEARUSDT',
    'EGLD-USDT': 'EGLDUSDT',
    'ZEC-USDT': 'ZECUSDT',
    'STX-USDT': 'STXUSDT',
    'ALGO-USDT': 'ALGOUSDT',
    'SNX-USDT': 'SNXUSDT',
    'RUNE-USDT': 'RUNEUSDT',
    'MKR-USDT': 'MKRUSDT',
    'CRV-USDT': 'CRVUSDT',
    'DYDX-USDT': 'DYDXUSDT',
    'LDO-USDT': 'LDOUSDT',
    '1INCH-USDT': '1INCHUSDT',
    'COMP-USDT': 'COMPUSDT',
    'ETH-BTC': 'ETHBTC'
  },
  'AscendEX': {
    'BTC-USDT': 'BTC/USDT',
    'ETH-USDT': 'ETH/USDT',
    'LTC-USDT': 'LTC/USDT',
    'BCH-USDT': 'BCH/USDT',
    'BNB-USDT': 'BNB/USDT',
    'SOL-USDT': 'SOL/USDT',
    'ADA-USDT': 'ADA/USDT',
    'XRP-USDT': 'XRP/USDT',
    'DOT-USDT': 'DOT/USDT',
    'DOGE-USDT': 'DOGE/USDT',
    'AVAX-USDT': 'AVAX/USDT',
    'MATIC-USDT': 'MATIC/USDT',
    'SHIB-USDT': 'SHIB/USDT',
    'TRX-USDT': 'TRX/USDT',
    'LINK-USDT': 'LINK/USDT',
    'ATOM-USDT': 'ATOM/USDT',
    'XMR-USDT': 'XMR/USDT',
    'WBTC-USDT': 'WBTC/USDT',
    'UNI-USDT': 'UNI/USDT',
    'XTZ-USDT': 'XTZ/USDT',
    'FIL-USDT': 'FIL/USDT',
    'EOS-USDT': 'EOS/USDT',
    'AAVE-USDT': 'AAVE/USDT',
    'SAND-USDT': 'SAND/USDT',
    'APE-USDT': 'APE/USDT',
    'GRT-USDT': 'GRT/USDT',
    'ETC-USDT': 'ETC/USDT',
    'NEAR-USDT': 'NEAR/USDT',
    'EGLD-USDT': 'EGLD/USDT',
    'ZEC-USDT': 'ZEC/USDT',
    'STX-USDT': 'STX/USDT',
    'ALGO-USDT': 'ALGO/USDT',
    'SNX-USDT': 'SNX/USDT',
    'RUNE-USDT': 'RUNE/USDT',
    'MKR-USDT': 'MKR/USDT',
    'CRV-USDT': 'CRV/USDT',
    'DYDX-USDT': 'DYDX/USDT',
    'LDO-USDT': 'LDO/USDT',
    '1INCH-USDT': '1INCH/USDT',
    'COMP-USDT': 'COMP/USDT',
    'ETH-BTC': 'ETH/BTC'
  },
  'BinanceUS': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    'ETH-BTC': 'ETHBTC',
    'LTC-USDT': 'LTCUSDT',
    'BCH-USDT': 'BCHUSDT',
    'BNB-USDT': 'BNBUSDT',
    'SOL-USDT': 'SOLUSDT',
    'ADA-USDT': 'ADAUSDT',
    'XRP-USDT': 'XRPUSDT',
    'DOT-USDT': 'DOTUSDT',
    'DOGE-USDT': 'DOGEUSDT',
    'AVAX-USDT': 'AVAXUSDT',
    'MATIC-USDT': 'MATICUSDT',
    'SHIB-USDT': 'SHIBUSDT',
    'TRX-USDT': 'TRXUSDT',
    'LINK-USDT': 'LINKUSDT',
    'ATOM-USDT': 'ATOMUSDT',
    'XMR-USDT': 'XMRUSDT',
    'WBTC-USDT': 'WBTCUSDT',
    'UNI-USDT': 'UNIUSDT',
    'XTZ-USDT': 'XTZUSDT',
    'FIL-USDT': 'FILUSDT',
    'EOS-USDT': 'EOSUSDT',
    'AAVE-USDT': 'AAVEUSDT',
    'SAND-USDT': 'SANDUSDT',
    'APE-USDT': 'APEUSDT',
    'GRT-USDT': 'GRTUSDT',
    'ETC-USDT': 'ETCUSDT',
    'NEAR-USDT': 'NEARUSDT',
    'EGLD-USDT': 'EGLDUSDT',
    'ZEC-USDT': 'ZECUSDT',
    'STX-USDT': 'STXUSDT',
    'ALGO-USDT': 'ALGOUSDT',
    'SNX-USDT': 'SNXUSDT',
    'RUNE-USDT': 'RUNEUSDT',
    'MKR-USDT': 'MKRUSDT',
    'CRV-USDT': 'CRVUSDT',
    'DYDX-USDT': 'DYDXUSDT',
    'LDO-USDT': 'LDOUSDT',
    '1INCH-USDT': '1INCHUSDT',
    'COMP-USDT': 'COMPUSDT',
    'ETH-BTC': 'ETHBTC'
  },
  'Bitget': {
    'BTC-USDT': 'BTCUSDT_SPBL',
    'ETH-USDT': 'ETHUSDT_SPBL',
    // ...add more pairs as needed
  },
  'Bybit': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'CoinbasePro': {
    'BTC-USDT': 'BTC-USDT',
    'ETH-USDT': 'ETH-USDT',
    // ...add more pairs as needed
  },
  'CryptoCom': {
    'BTC-USDT': 'BTC_USDT',
    'ETH-USDT': 'ETH_USDT',
    // ...add more pairs as needed
  },
  'LBank': {
    'BTC-USDT': 'btc_usdt',
    'ETH-USDT': 'eth_usdt',
    // ...add more pairs as needed
  },
  'MEXC': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'OneInch': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'PancakeSwap': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'Phemex': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'Poloniex': {
    'BTC-USDT': 'BTC_USDT',
    'ETH-USDT': 'ETH_USDT',
    // ...add more pairs as needed
  },
  'Probit': {
    'BTC-USDT': 'BTC-USDT',
    'ETH-USDT': 'ETH-USDT',
    // ...add more pairs as needed
  },
  'SushiSwap': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'Uniswap': {
    'BTC-USDT': 'BTCUSDT',
    'ETH-USDT': 'ETHUSDT',
    // ...add more pairs as needed
  },
  'WhiteBIT': {
    'BTC-USDT': 'BTC_USDT',
    'ETH-USDT': 'ETH_USDT',
    // ...add more pairs as needed
  }
};

for (const ex in pricesByExchange) {
  const pairs = Object.keys(pricesByExchange[ex]);
  if (pairs.includes("BTC-USDT") && pairs.includes("ETH-USDT") && pairs.includes("ETH-BTC")) {
    console.log(`Exchange ${ex} has all required pairs for triangular/inter-asset`);
  } else {
    console.log(`Exchange ${ex} missing pairs:`, ["BTC-USDT", "ETH-USDT", "ETH-BTC"].filter(p => !pairs.includes(p)));
  }
}

export const SYMBOL_ALIASES = {
  "MATIC": "POL",
  "LUNA": "LUNC",
  // Add more as needed
};

export function canonicalizeSymbol(symbol) {
  const [base, quote] = symbol.split("-");
  const baseAlias = SYMBOL_ALIASES[base] || base;
  const quoteAlias = SYMBOL_ALIASES[quote] || quote;
  return `${baseAlias}-${quoteAlias}`;
}
